spring:
  application:
    name: media-cataloger-api
  profiles:
    active: test

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: TRACE


token-config:
  issuer: "AURA CORPORATION"
  expirationTimeSeconds: 10800
  secretKey: "Dtpb2ley7RmAN8GDKcWNpnox31KZvZiZ"
