spring:
  application:
    name: media-cataloger-api
  profiles:
    active: ${ENVIRONMENT}

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: TRACE
