spring:
  application:
    name: media-cataloger-db
  datasource:
    url: jdbc:h2:file:./database;AUTO_SERVER=TRUE
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

