name: esteira-ci-pr

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git actions
        uses: actions/checkout@v2
      - name: Technology setup
        uses: actions/setup-java@v1
        with:
          java-version: 17

  build:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [setup]
    steps:
      - name: Checkout git actions
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: mvn clean install
      - name: Production Build
        run: mvn package

  build-image:
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - name: Docker QEMU setup
        uses: docker/setup-qemu-action@v2

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:pr